version: '3.3'
services:
  evepraisal:
    image: evepraisal:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 64M