//Lists obtained here: https://everef.net/

const ore = [
    "veldspar",
    "concentrated veldspar",
    "dense veldspar",
    "scordite",
    "condensed scordite",
    "massive scordite",
    "pyroxeres",
    "solid pyroxeres",
    "viscous pyroxeres",
    "plagioclase",
    "azure plagioclase",
    "rich plagioclase",
    "omber",
    "silvery omber",
    "golden omber",
    "kernite",
    "luminous kernite",
    "fiery kernite",
    "jaspet",
    "pure jaspet",
    "pristine jaspet",
    "hemorphite",
    "vivid hemorphite",
    "radiant hemorphite",
    "hedbergite",
    "vitric hedbergite",
    "glazed hedbergite",
    "gneiss",
    "iridescent gneiss",
    "prismatic gneiss",
    "dark ochre",
    "onyx ochre",
    "obsidian ochre",
    "crokite",
    "sharp crokite",
    "crystalline crokite",
    "spodumain",
    "bright spodumain",
    "gleaming spodumain",
    "bistot",
    "triclinic bistot",
    "monoclinic bistot",
    "arkanor",
    "crimson arkonor",
    "prime arkonor",
    "mercoxit",
    "magma mercoxit",
    "vitreous mercoxit"
];

const compressed_ore = [
    "compressed veldspar",
    "compressed concentrated veldspar",
    "compressed dense veldspar",
    "compressed scordite",
    "compressed condensed scordite",
    "compressed massive scordite",
    "compressed pyroxeres",
    "compressed solid pyroxeres",
    "compressed viscous pyroxeres",
    "compressed plagioclase",
    "compressed azure plagioclase",
    "compressed rich plagioclase",
    "compressed omber",
    "compressed silvery omber",
    "compressed golden omber",
    "compressed kernite",
    "compressed luminous kernite",
    "compressed fiery kernite",
    "compressed jaspet",
    "compressed pure jaspet",
    "compressed pristine jaspet",
    "compressed hemorphite",
    "compressed vivid hemorphite",
    "compressed radiant hemorphite",
    "compressed hedbergite",
    "compressed vitric hedbergite",
    "compressed glazed hedbergite",
    "compressed gneiss",
    "compressed iridescent gneiss",
    "compressed prismatic gneiss",
    "compressed dark ochre",
    "compressed onyx ochre",
    "compressed obsidian ochre",
    "compressed crokite",
    "compressed sharp crokite",
    "compressed crystalline crokite",
    "compressed spodumain",
    "compressed bright spodumain",
    "compressed gleaming spodumain",
    "compressed bistot",
    "compressed triclinic bistot",
    "compressed monoclinic bistot",
    "compressed arkanor",
    "compressed crimson arkonor",
    "compressed prime arkonor",
    "compressed mercoxit",
    "compressed magma mercoxit",
    "compressed vitreous mercoxit"
];

const salavage = [
    "alloyed tritanium bar",
    "armor plates",
    "artificial neural network",
    "broken drone transceiver",
    "burned logic circuit",
    "capacitor console",
    "charred micro circuit",
    "conductive polymer",
    "conductive thermoplastic",
    "contaminated lorentz fluid",
    "contaminated nanite compound",
    "current pump",
    "damaged artificial neural network",
    "defective current pump",
    "drone transceiver",
    "enhanced ward console",
    "fried interface circuit",
    "impetus console",
    "intact armor plates",
    "intact shield emitter",
    "interface circuit",
    "logic circuit",
    "lorentz fluid",
    "malfunctioning shield emitter",
    "melted capacitor console",
    "micro circuit",
    "nanite compound",
    "power circuit",
    "power conduit",
    "scorched telemetry processor",
    "single-crystal superalloy i-beam",
    "smashed trigger unit",
    "tangled power conduit",
    "telemetry processor",
    "thruster console",
    "trigger unit",
    "tripped power circuit",
    "ward console"
];

const pi_fuel = [
    "aqueous liquids",
    "base metals",
    "ionic solutions",
    "noble gas",
    "noble metals",
    "non-cs crystals",
    "water",
    "reactive metals",
    "toxic metals",
    "electrolytes",
    "oxygen",
    "precious metals",
    "chiral structures",
    "consumer electronics",
    "coolant",
    "enriched uranium",
    "mechanical parts",
    "robotics"
]

const pi_commodies_without_fuel = [
    "autotrophs",
    "carbon compounds",
    "complex organisms",
    "felsic magma",
    "heavy metals",
    "micro organisms",
    "planktic colonies",
    "reactive gas",
    "suspended plasma",
    "industrial fibers",
    "biofuels",
    "proteins",
    "silicon",
    "bacteria",
    "biomass",
    "oxidizing compound",
    "plasmoids",
    "biocells",
    "construction blocks",
    "fertilizer",
    "gen. enhanced livestock",
    "livestock",
    "microfiber shielding",
    "miniature electronics",
    "nanites",
    "oxides",
    "polyaramids",
    "polytextiles",
    "rocket fuel",
    "silicate glass",
    "superconductors",
    "supertensile plastics",
    "synthetic oil",
    "test cultures",
    "transmitter",
    "viral agent",
    "water-cooled cpu",
    "biotech research reports",
    "camera drones",
    "condensates",
    "cryoprotectant solution",
    "data chips",
    "gel-matrix biopaste",
    "guidance systems",
    "hazmat detection systems",
    "hermetic membranes",
    "high-tech transmitters",
    "industrial explosives",
    "neocoms",
    "nuclear reactors",
    "planetary vehicles",
    "smartfab units",
    "supercomputers",
    "synthetic synapses",
    "transcranial microcontrollers",
    "ukomi super conductors",
    "vaccines",
    "broadcast node",
    "integrity response drones",
    "nano-factory",
    "organic mortar applicators",
    "recursive computing module",
    "self-harmonizing power core",
    "sterile conduits",
    "wetware mainframe"
]

const moon_ore = [
    "bitumens",
    "bountiful loparite",
    "bountiful monazite",
    "bountiful xenotime",
    "bountiful ytterbite",
    "brimful bitumens",
    "brimful coesite",
    "brimful sylvite",
    "brimful zeolites",
    "carnotite",
    "chromite",
    "cinnabar",
    "cobaltite",
    "coesite",
    "copious cobaltite",
    "copious euxenite",
    "copious scheelite",
    "copious titanite",
    "euxenite",
    "glistening bitumens",
    "glistening coesite",
    "glistening sylvite",
    "glistening zeolites",
    "glowing carnotite",
    "glowing cinnabar",
    "glowing pollucite",
    "glowing zircon",
    "lavish chromite",
    "lavish otavite",
    "lavish sperrylite",
    "lavish vanadinite",
    "loparite",
    "monazite",
    "otavite",
    "pollucite",
    "replete carnotite",
    "replete cinnabar",
    "replete pollucite",
    "replete zircon",
    "scheelite",
    "shimmering chromite",
    "shimmering otavite",
    "shimmering sperrylite",
    "shimmering vanadinite",
    "shining loparite",
    "shining monazite",
    "shining xenotime",
    "shining ytterbite",
    "sperrylite",
    "sylvite",
    "titanite",
    "twinkling cobaltite",
    "twinkling euxenite",
    "twinkling scheelite",
    "twinkling titanite",
    "vanadinite",
    "xenotime",
    "ytterbite",
    "zeolites",
    "zircon"
]

const moon_materials = [
    "atmospheric gases",
    "cadmium",
    "caesium",
    "chromium",
    "cobalt",
    "dysprosium",
    "evaporite deposits",
    "hafnium",
    "hydrocarbons",
    "mercury",
    "neodymium",
    "platinum",
    "promethium",
    "scandium",
    "silicates",
    "technetium",
    "thulium",
    "titanium",
    "tungsten",
    "vanadium"
]

const gas_clouds = [
    "amber cytoserocin",
    "amber mykoserocin",
    "azure cytoserocin",
    "azure mykoserocin",
    "celadon cytoserocin",
    "celadon mykoserocin",
    "fullerite-c28",
    "fullerite-c32",
    "fullerite-c320",
    "fullerite-c50",
    "fullerite-c540",
    "fullerite-c60",
    "fullerite-c70",
    "fullerite-c72",
    "fullerite-c84",
    "golden cytoserocin",
    "golden mykoserocin",
    "lime cytoserocin",
    "lime mykoserocin",
    "malachite cytoserocin",
    "malachite mykoserocin",
    "vermillion cytoserocin",
    "vermillion mykoserocin",
    "viridian cytoserocin",
    "viridian mykoserocin"
]

module.exports = {
    ore: ore,
    compressed_ore: compressed_ore,
    salavage: salavage,
    pi_fuel: pi_fuel,
    pi_commodies_without_fuel: pi_commodies_without_fuel,
    moon_ore: moon_ore,
    moon_materials: moon_materials,
    gas_clouds: gas_clouds
}